package exam_database;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class CreateBookTable {
    public static void main(String[] args) {

        Connection conn = null;
        PreparedStatement pstmt = null;

        try {
            System.out.println("테이블을 생성합니다.");

            conn = DBConnectionUtil.getConnection("xepdb1", "javauser", "java1234");

            String query = """
                CREATE TABLE book (
                    book_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                    title VARCHAR2(200) NOT NULL,
                    author VARCHAR2(100) NOT NULL,
                    publisher VARCHAR2(100) NOT NULL,
                    publish_date DATE NOT NULL,
                    price NUMBER(10) NOT NULL,
                    CONSTRAINT book_pk PRIMARY KEY(book_id)
                )
                """;

            pstmt = conn.prepareStatement(query);
            pstmt.executeUpdate();

            int insertCount = pstmt.executeUpdate();

        } catch (ClassNotFoundException e) {
            System.err.println("[드라이버 ERROR] 드라이버를 찾을 수 없습니다.");
        } catch (SQLException e) {
            System.err.println("[쿼리문 ERROR] \n" + e.getMessage());
        } finally {
            try {
                if(pstmt != null) pstmt.close();
                if(conn != null) conn.close();
            } catch (Exception e) {
                System.err.println("[Close ERROR] \n" + e.getMessage());
            }
        }
    }
}